spring.application.name=CNProject
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/chatFtpDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=talfAR03!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
# FTP
ftp.server.host=127.0.0.1
ftp.server.port=21
ftp.server.username=ftpuser1
ftp.server.password=abcd1234
ftp.server.base-directory=/Data
# WebSocket Config
server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
app.websocket.endpoint=/ws
app.websocket.topic.prefix=/topic
app.websocket.app.prefix=/app
# 30 minutes session timeout (in seconds)
server.servlet.session.timeout=1800
# Increase FTP timeout settings (in milliseconds)
spring.integration.ftp.session.read-timeout=60000
spring.integration.ftp.session.connect-timeout=60000
spring.integration.ftp.session.data-timeout=60000
# Increase upload size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Connection settings
ftp.client.connection-retry-delay=1000
ftp.client.max-retries=2
ftp.client.keep-alive=true